name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nuget-restore:
    name: NuGet Restore
    uses: kirandevops1993/NUGET-REUSABLE/.github/workflows/nuget-reusable.yml@main
    with:
      solution: "**/*.sln"
      nugetConfigPath: ""
      packagesDirectory: ""
      verbosity: "true"
      nuGetRestoreArgs: ""
      restoreMode: "true"
      noCache: false
      nuGetVersion: "true"
      nuGetPath: ""
      searchPattern: "**/*.csproj"
      outputdir: "$(Build.ArtifactStagingDirectory)"
      includeSymbols: false
      versionByBuild: false
      versionEnvVar: ""
      majorVersion: 1
      minorVersion: 0
      patchVersion: 0
      configurationToPack: "$(BuildConfiguration)"
      buildProperties: ""
      nuGetAdditionalArgs: ""
      nuGetFeedType: "internal"
      feedName: ""
      skipDuplicate: false

  build-solution:
    name: Build Solution
    needs: nuget-restore
    uses: kirandevops1993/MS-BUILD-TASKS-REUSABLE-/.github/workflows/msbuildtasks-reusable.yml@main
    with:
      solution: .sln
      vsVersion: latest
      msbuildArgs: "/p:OutDir=$(build.stagingDirectory) /p:DeployOnBuild=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p: SkipInvalidConfigurationstrue /p:PackageLocation=$(udClientLocation)"
      platform: "$(BuildPlatform)"
      configuration: "$(BuildConfiguration)"
      clean: true
      maximumCpuCount: false
      restoreNugetPackages: false
      msbuildArchitecture: x86
      logProjectEvents: true
      createLogFile: false
      logFileVerbosity: "detailed"

  run-powershell-script:
    name: Run PowerShell Script
    needs: build-solution
    uses: kirandevops1993/POWERSHELL-REUSABLE-/.github/workflows/powershellreusable.yml@main
    with:
      script-path: ".github/workflows/Get-HostName.ps1"
      script-arguments: ""
      inline-script: ""
